In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [5]:
model=load_model('model.h5')
with open('onehot_encoder_geo.pkl', 'rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl','rb' ) as file:
    label_encoder_gender= pickle.load(file)

with open('scaler.pkl','rb' ) as file:
    scaler= pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [6]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [8]:
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df= pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

C:\Users\Ritesh Kandwal\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [9]:
input_df=pd.DataFrame([input_data])

In [10]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [11]:
input_df['Gender'] =label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [13]:
input_df=pd.concat([input_df.drop("Geography", axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [14]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [15]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

array([[0.02795561]], dtype=float32)

In [16]:
prediction_proba=prediction[0][0]
prediction_proba

0.02795561

In [17]:
if prediction_proba >0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn

In [18]:
!git init
!git add .

Reinitialized existing Git repository in C:/Users/Ritesh Kandwal/Documents/4 STUDY/PYTHON/projects/udemyproject/.git/

warning: in the working copy of '.ipynb_checkpoints/experiments-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'experiments.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'prediction.ipynb', LF will be replaced by CRLF the next time Git touches it

In [19]:
!git commit -m "intial commit"

[main b7771f9] intial commit
 8 files changed, 1023 insertions(+), 377 deletions(-)
 create mode 100644 .ipynb_checkpoints/prediction-checkpoint.ipynb
 create mode 100644 logs/fit/20260414-220452/train/events.out.tfevents.1776185752.RITESHKANDWAL.21732.0.v2
 create mode 100644 logs/fit/20260414-220452/validation/events.out.tfevents.1776185755.RITESHKANDWAL.21732.1.v2
 rename label_encoder_geo.pkl => onehot_encoder_geo.pkl (100%)
 create mode 100644 prediction.ipynb

In [21]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

Everything up-to-date